fix: error with anonymous functions in route def
Routes definitions containing anonymous functions instead of a reference to a Controller make AutoSwagger.writeFile method fails with :
Error: ENOENT: no such file or directory, open 'app/Controllers/Http/.ts'
Checking route.meta....method name allows to exclude those routes.